version: "3.4"
services:
  db:
    image: postgres:alpine
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5433:5432
  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    hostname: message-broker-service
    env_file: .env
    ports:
      - 5672:5672
      - 15672:15672
