name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_ENVIRONMENT: IntegrationTesting
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Start docker test container
      run: docker-compose -f docker-compose.testing.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Install dotnet-ef tool
      run: dotnet tool install --global dotnet-ef --version 3.1.0
    - name: Apply Migrations
      run: dotnet ef database update -s Microservice.Api.csproj -p Microservice.Db.csproj -c MicroserviceDbContext
    - name: Test
      run: dotnet test --no-restore --verbosity normal
